services:
  kong:
    ports: !override
      - "127.0.0.1:${KONG_HTTP_PORT:-8000}:8000/tcp"

  supavisor:
    ports: !override
      - "127.0.0.1:${POSTGRES_PORT:-5432}:5432"
      - "127.0.0.1:${POOLER_PROXY_PORT_TRANSACTION:-6543}:6543"
